# meta-xtobe-guardian — Yocto layer for the Xtobe microVM OS
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-xtobe-guardian"
BBFILE_PATTERN_meta-xtobe-guardian = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-xtobe-guardian = "10"

LAYERSERIES_COMPAT_meta-xtobe-guardian = "scarthgap"
